### PR TITLE
Remove inactive users

### PR DESCRIPTION
**Pull request by damacus**
# Description

Describe what this change achieves

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Raboo** [comment]
Personally I've ignored most repositories except maybe 5-6 where I actually have done some participation or a bit of interest. I try to do a review occasionally when time permits. But I use chef less and less. It's up to you if you want me removed as I are not super active and that is completely understandable, but if you don't mind I can stay for the time being.

**Comment by jeffbyrnes** [comment]
@damacus probably best to drop me, while I’d love to keep contributing, it’s just not in the cards for me for the time being.

**Comment by damacus** [comment]
@xorima and I have been chatting about how we can assign moderators to cookbooks without needing to be team members, something like home-assistant or k8s. Where people will be on a list and be notified via a bot.

**Comment by jakauppila** [comment]
> Personally I've ignored most repositories except maybe 5-6 where I actually have done some participation or a bit of interest. I try to do a review occasionally when time permits. But I use chef less and less. It's up to you if you want me removed as I are not super active and that is completely understandable, but if you don't mind I can stay for the time being.

I'm in the same boat as @Raboo; there's a handful of repos we use and would be interested in maintaining as needed, but I could also do that on the outside and just watch those repositories and contribute fixes to issues as they arise.

There isn't a lot of movement in our Chef usage and will continue to shrink in the coming years as we continue to push more workloads to containers.

**Comment by kitchen-porter** [comment]
Ace, which repos are they?

We'll start makin a list

**Comment by Raboo** [comment]
> @xorima and I have been chatting about how we can assign moderators to cookbooks without needing to be team members, something like home-assistant or k8s. Where people will be on a list and be notified via a bot.

There is a small downside to this, the contributors won't be eligible for Free Github Code Pilot.

**Comment by damacus** [comment]
So there's the rub, we probably would expect more contributions to be a core member at that point. We could show that as a benefit. 

Right now, people are indeed getting Co-Pilot for very little contribution back to the org.

**Comment by jakauppila** [comment]
> Ace, which repos are they? We'll start makin a list

It's not as big of a list as I would have thought:
- aws
- iis
- java
- tomcat
- trusted_certificate

**Review by jeffbyrnes — APPROVED** [review]

**Comment by fernandoaleman** [comment]
> Calling all current members!
> 
> We're looking at removing current members who are no longer actively participating in code reviews. This mean we can increase our GitHub membership (to increase our runners)
> 
> As this is an opensource org, you can of course still contribute. However, right now we're probably just destroying your notifications. If you'd like to stay please let me know in this post by the end of the month (end of April 2023).
> 
> @TD-4242, @BackSlasher, @brianhays, @mengesb, @flaccid, @rshade, @RyanJarv, @iennae, @sbotman, @shoekstra, @teknofire, @Raboo, @snkutlu, @ev0ldave, @gsreynolds, @atheiman, @scopenco, @jeffbyrnes, @pschaumburg, @sinfomicien, @majormoses, @Stromweld, @brianbianco, @fernandoaleman, @zmaupin, @ryantiger658, @mohitsethi, @darwin67, @marcosvm, @mbaitelman, @mburns, @zimmerry, @limitusus, @EMH333, @nuclearsandwich, @jakauppila, @frank-m, @detjensrobert, @mvangoor, @stevendanna, @derekgroh 

@damacus I'd like to stay on if that's okay 👍

**Comment by mengesb** [comment]
It's ok to pr me out

**Comment by mbaitelman** [comment]
I'd like to stick around and take responsibility for a few repos.
I am tweaking my role at work to allow for more open-source work as part of my job duties.

**Comment by nuclearsandwich** [comment]
I've had a very hard time allocating for sous-chefs time but I have several major projects for https://github.com/sous-chefs/jenkins that are in my queue. If possible I would like to remain a maintainer.

**Comment by mohitsethi** [comment]
> 

I would like to stay, if that's okay.

**Comment by majormoses** [comment]
Sorry I have not been active for a while, I do from time to time review stuff. As others I am in a similar situation where our chef usage is shrinking. Once my org is entirely off chef I think I will ask to be removed to save my inbox.

**Comment by damacus** [comment]
That sounds excellent @limitusus however I can see there haven't been any commits to that repository except for standard files for 2.5 years. 

This is a cost-saving exercise for us, and whilst we *love* having a large community. A large community can still be helping out on Slack, and commenting on pull requests without needing to be in the organisation. 👍🏼

**Review by Raboo — DISMISSED** [review]
👍

**Pull request merged**
